[versions]

# Android
androidGradlePlugin = "8.2.0"

# Kotlin
kotlin = "1.9.21"
coroutines = "1.7.3"
serialization = "1.6.2"
datetime = "0.5.0"
ksp = "1.9.21-1.0.16"

# Dagger
dagger = "2.50"
androidxhilt = "1.1.0"

# AndroidX
androidx-activity = "1.8.2"
androidx-appcompat = "1.6.1"
androidx-benchmark = "1.2.2"
androidx-browser = "1.7.0"
androidx-constraintlayout = "2.1.4"
androidx-core = "1.12.0"
androidx-datastore = "1.0.0"
androidx-fragment = "1.6.2"
androidx-lifecycle = "2.6.2"
androidx-navigation = "2.7.6"
androidx-profileinstaller = "1.3.1"
androidx-room = "2.6.1"
androidx-startup = "1.1.1"
androidx-window = "1.2.0"
androidx-work = "2.9.0"
androidx-compose-material3 = "1.1.2"

# Google
gms = "4.4.0"
play-appupdate = "2.1.0"
admob = "22.6.0"
firebase-bom = "32.7.0"
firebase-crashlytics = "2.9.9"
firebase-perf = "1.4.2"

# Compose
compose-bom = "2023.10.01"
composeCompiler = "1.5.6"
accompanist = "0.32.0"
peekaboo = "0.3.0"

# Etc
coil = "2.5.0"
dependencyGuard = "0.3.2"
retrofit = "2.9.0"
retrofit-serialization = "1.0.0"
timber = "5.0.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
material = "1.11.0"
okhttp = "4.12.0"

[libraries]

# Android
android-desugar-jdk = "com.android.tools:desugar_jdk_libs:2.0.4"

# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# Dagger
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
dagger-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }

androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidxhilt" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxhilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxhilt" }

# AndroidX
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core"}
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }

androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-compose-material3" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "androidx-compose-material3" }

androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidx-profileinstaller" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }

androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup" }
androidx-window = { module = "androidx.window:window", version.ref = "androidx-window" }

androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "androidx-work" }

# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material = { module = "androidx.compose.material:material" }
compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics" }

accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }

peekaboo-ui-android = { module = "io.github.team-preat:peekaboo-ui-android", version.ref = "peekaboo" }
peekaboo-image-picker-android = { module = "io.github.team-preat:peekaboo-image-picker", version.ref = "peekaboo" }

# Test
test-junit =  "junit:junit:4.13.2"

androidx-test-core = "androidx.test:core-ktx:1.5.0"
androidx-test-rules = "androidx.test:rules:1.5.0"
androidx-test-runner = "androidx.test:runner:1.5.2"
androidx-test-ext-truth = "androidx.test.ext:truth:1.5.0"
androidx-test-ext-junit = "androidx.test.ext:junit-ktx:1.1.5"
androidx-test-espresso = "androidx.test.espresso:espresso-core:3.5.1"
androidx-test-uiautomator = "androidx.test.uiautomator:uiautomator:2.2.0"

# Google

google-play-appupdate = { module = "com.google.android.play:app-update-ktx", version.ref = "play-appupdate" }
google-admob = { module = "com.google.android.gms:play-services-ads", version.ref = "admob" }

# https://firebase.google.com/support/release-notes/android#latest_sdk_versions
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-cloudmessaging = { module = "com.google.firebase:firebase-messaging" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-dynamiclinks = { module = "com.google.firebase:firebase-dynamic-links" }
firebase-performance = { module = "com.google.firebase:firebase-perf" }
firebase-remoteconfig = { module = "com.google.firebase:firebase-config" }

# OkHttp

okhttp3-okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }

# Etc

coil-runtime = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-serialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-serialization" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Dependencies of the included build-logic
android-pluginGradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit115 = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
gms = { id = "com.google.gms.google-services", version.ref = "gms" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }
firebase-performance = { id = "com.google.firebase.firebase-perf", version.ref = "firebase-perf" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
